version: '3.5'
services:
  bowl-scoring-server:
    image: raminarmanfar/bowl-scoring-backend
    container_name: scoring-server
    build:
      context: ./bowl-scoring-backend
    environment:
      - HTTP_PORT=3400
    ports:
      - 3400:3400
    restart: always

  bowl-scoring-frontend:
    image: raminarmanfar/bowl-scoring-frontend
    container_name: scoring-ui
    restart: always
    ports:
      - 3500:80
    depends_on:
      - bowl-scoring-server
    links:
      - bowl-scoring-server
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
    build:
      context: ./bowl-scoring-frontend
      dockerfile: Dockerfile

